url: 'http://39.107.252.61:9125,http://39.107.252.61:9125'
target_deadline: '60000'
account_ids:
  - '698270381115387253'
  - '14277462372480454007'
plot_dirs:
  - '/home/huzy/plot'


# BHD 双挖配置, 不需要双挖的，删除这个部分
additional_headers:
  pk: 921d504177baa811c9f0fa73399a25c0adbd5188f80ba2b..............
  chaintype: BHD

# 如果不填写CPU， 默认就是avx2.
# 使用cpuz查看cpu支持的指令集，填写sse,avx或者avx2.
# 性能 sse < avx < avx2
# 但是不同机器支持的指令集不相同，需要自己去看自己的cpu支持哪种指令集
cpu: avx

